version: '2'

services:
  app:
    image: 'operation-volcano:1.0.0'
    build:
      context: .
    container_name: operation-volcano
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=verysecretpassword
  postgres:
    image: 'postgres:13.1'
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=verysecretpassword