spring:
  application:
    name: operation-volcano
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: verysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true